---
language: python
python:
    - '3.6'
env:
    matrix:
        - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
    global:
        - secure: npvVkPdt57/+ZFpt+ylvUrDnvvS9QZy0HiTjSbpFvMx6sdN8kA9u4SdPpeQ7Z07bhoFnu1rG2WyVxs0TfMjwrrMLTS2osiLWePBg2IQ3Lfdyi5oT1yD+lj2Z3MC6oOJnitV1XIFv7fq0eTkogoYc68w6FwfEcZLZx8uuWph9rrcObZhZmYXqYFbhBe1F3ZSTGUbarE/+EMCFQLF9PlElJlnHrITZoy1hy+XCqGdlRLrh1L9oXDcFWPeF5ZNkH+Tb4//MQ1MAsPSTP4/d/5ODBf5Ug0qNLQMxzH0ivt4uPZ06fkWCo4Q9WzJ4TslFWWK0Ycxq4nptU2LUvvnPZdgLt3eHAAP99MNI1XvWw+nh8N1K2IS4Wf2XW/SZIRqNMrMQF8N+1wpTAQnLquXn1dG6HKZXOXfi+jeEgCpsOVNRsaNdiRCclVpCRN4gu6HYvqhnvXNSIbH4s03xj4+GbliH89/EVSkP+tizaGLpZdQk8GywPGxUvLRl+SHFhreO5X5HpvlOq8w0lWGN1baGX+vD60gW605qHZ/Qz6EiU6d7s+7z9r6ICNSn2oxOtPOxf7wjb8r3N3w7ZrmFKCpGPn1HYXZCdiL9O49EbxhkGa7Gd9zEBRVQnWXFA2pohY7G7p7Wtn2SWSXWKhvFRLiOqF7X0/NAkKn/Ijfr4SWZ0V1JQDs=
        - secure: kR9gIvHz31eIkZxyjJPeMuiE+dmb+eSsy8pO+JhScI5S8Ww4iAET5WJ2qfWLzJh/agoDk2Wnb0hNnw75vx+crtquFN/u6mk04KfORjxPFGxkQppNmCrE2a0SoNnW/yGiXwmTTRR6EvU+cOOak4yuPSVupdHNAPQzoqUYcykxihJyZ8U6iGvKVLjymwOjhklMOrXPndEFJbo5oqaw06qmthlubFCDb8IfT1jzbvVjAshRIY+MC0GusbvgQzY7MhQd7u/2eHQYQvHIaEFja+0Y8SQv8tilrgaHvg8CTb57c05ol9JHK1C/D3bdh+5D0PKGc/mRk29tnvWxWJfzNHMlkdex/c19nbz2GXjrDyu/rrdoI8sCUhIgmwX4FjWAwYknH8DBEmX+9m7To3P+7fsy4C+xSvDueg0zW4BdSBmMzRA2r2FIRQYgWsdG73EBQNg//7WZS6g8W17AaxJJlsUYHpGsy64mCA7XM46x+f8vJAFgTzngBB6lYYbqA9P/fKtDITenOLJHfZtjCH6tg5VJHSrSpiZ2Lzgxq3ETCQIgwUH20LhKY5csdPWA34T2A4pZYWo1yhI25Qs7Q3LrbfbGqXkr+e3xoWMBHn1j8GznisVOgg6KF+JscCNFqpkMtFynC68F2WCsUgI/hK7hqzA78PIYv/m0cAsXLC5u5A+MImM=
        - secure: nhYjTqd/eTWGl72AhSjR4OT+LNbrvhGQozMm2LDYWROALUkZQydoOp/ItkueIcwubj45qELXmRcYICRXBmPi++EbFii46s0hFwO6DosaiQAm1ZsG/hYWFgWZvPYy0rRtn16jsezFbMCHj6epFAUvqYeop3w6yHeUa+ubgTt3gUTlEmmGN2q+/aTr2VVz1Y7KDNIVeTPoPrdNMgiBEZ1AXfDjUxNefixuR79Ymc9cjzBbJxQGSlvq2PcwpdI2kOohDhaAF+ThG8bsjUyxShAgJvhAxceYcx0s/C6toUYE+jsbA27qMy9v7Vb8PjH29dO7a6hRWBuky9l1iSOrmHOErsSP2qvhMxUXqYqLVLOvULRTTm4FSrWsaCtHgnFN4E+qClOwDs0CMpO7ohllLJ2izh6gBJaTTg800+CUCbT45RZStxPWCEpiHMmtx14Uq+6qIm4+N+YPKHiGmP+Sw+K0npXsNlVDV8IoxKYq+YIFHRi1pva5/TcPAHuKndUWumUYZCX1IUHtHIrKvXRB3fl2qoWqM9/FP5VcApjtU5JtLxLj05+VNIP5dTxEmFw0aAhKp+KTNXX9dltAawSqATCbDDgzoH+XBEpdQzufPHDzK8VHY4CO5ls4UvwK9nYD86B1V1NQrpT8hZstEBMv2Mpx9IT/xaaHtJUWAtLyrGoPt6o=
before_install:
    - openssl aes-256-cbc -K $encrypted_65b487483407_key -iv $encrypted_65b487483407_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - mv google_compute_engine ~/.ssh/
    - chmod 0600 ~/.ssh/google_compute_engine
install:
    - pip install molecule apache-libcloud pycrypto
script:
    - molecule --debug create
    - molecule --debug converge
    - molecule --debug verify
after_script:
    - molecule destroy
notifications:
    slack:
        secure: VobI+sYgsPzTICRxtsc13NkdVsKqB91qdiRfyciQukhARUpDbRbgVbjL1oY9J4Kj0fjGNjJeFJiYmvDch9vgFuToHD5HJHXzmP/xLtk0I6SikV/H2fEPTUkdUR87RBEYJRwhCiwjoVb43Fpqsi2iI6FJ4CWLaUIla2ZRMcSEUR7Spa/q4wG6W/T2iqM/yn7bRGeQrKWqcsA3HQ+cuA/YMD41XKL+cy4xjORQ9TrZXfG2bkNVcPtD64tZQkSiIR8PC+hz1FgVbTp67iMJ7EvVbPtJIYhCEmMHZN3qZ9jFOEjboIPfdNUxOWn6RzAcXueNAWzdD5rmcOL0YcNUddVORr4uPLvxrtS1zqJwkiJs4FKz+LS9yqSEFEhWwZydHzDn3XHCwVfUAMdAXqmFuJwgZs6Vt5zqAyPDri6dftOH3JquChgGWHmP5voogdFZUy9ilGK/CpyfJxKzb+TVdmLSeTOq8pz0flWebOCbYEAlocxYhvGFSYa11TbWNYeTlhMKdLwDFDqYaSSST6BNJpXtL8of5784sI8/5fY889ITrMhmFT3pxCXMqcPvbkSR1Cm3vLavyYk3K4m7MPYvJYb7K8HzT1Rl2RUNxLwmDIEbczAOvJeX9kJEQkn3sLRDt1vihMwhWoUyHWIbcYdtK24zHHciJQTXuBVILwwUFVBu5uc=
